personelimmvc/Models/EntityFramework/Departman.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace personelimmvc.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departman
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Departman()
        {
            this.personel = new HashSet<personel>();
        }
    
        public int id { get; set; }
        public string ad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personel> personel { get; set; }
    }
}

personelimmvc/Models/EntityFramework/Model1.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace personelimmvc.Models.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class personelim : DbContext
    {
        public personelim()
            : base("name=personelim")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Departman> Departman { get; set; }
        public virtual DbSet<personel> personel { get; set; }
    }
}

personelimmvc/Models/EntityFramework/Model1.Designer.cs
// T4 code generation is enabled for model 'c:\users\omer\documents\visual studio 2015\Projects\personelimmvc\personelimmvc\Models\EntityFramework\Model1.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

personelimmvc/Models/EntityFramework/Model1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

personelimmvc/Models/EntityFramework/personel.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace personelimmvc.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class personel
    {
        public int id { get; set; }
        public Nullable<int> departmanid { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public Nullable<short> maas { get; set; }
        public Nullable<System.DateTime> dogumtarihi { get; set; }
        public Nullable<bool> cinsiyet { get; set; }
        public Nullable<bool> evlimi { get; set; }
    
        public virtual Departman Departman { get; set; }
    }
}

personelimmvc/Controllers/departmanController.cs
using personelimmvc.Models.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace personelimmvc.Controllers
{
    public class departmanController : Controller
    {
        personelim bag = new personelim();
        // GET: departman
        public ActionResult Index()
        {
            var model = bag.Departman.ToList();
            return View(model);
        }
    }
}

personelimmvc/Controllers/personelController.cs
using personelimmvc.Models.EntityFramework;
using personelimmvc.view_models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace personelimmvc.Controllers
{
    public class personelController : Controller
    {
        personelim bag = new personelim();
        // GET: personel
        public ActionResult Index()
        {
            var model = bag.personel.ToList();
            return View(model);
        }
        public ActionResult Yeni()
        {
            var model = new Personelformviewmodels()
            {// modele Personelformviewmodel de bulunan departmanlar nesnesine
// departmanlar tablosunu listeleyerek  attı
                departmanlar = bag.Departman.ToList()

            };

            return View("Personelform",model);
            // personelform sayfasına da modeli gönderdi
        }
        public ActionResult kaydet(personel personel) {

            
            if (personel.id==0)// 0 olması kaydetme anlamına gelecek
            {
                bag.personel.Add(personel);  
            }
            else
            {

            }
            bag.SaveChanges();
            return RedirectToAction("Index");
        }

    
    }
}

personelimmvc/Views/departman/Index.cshtml
@using personelimmvc.Models.EntityFramework
@model List<Departman>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/shared/Layout.cshtml";
}
<h2>SAYFAM</h2>
@*<table class="table table-bordered">
    <thead>
        <tr>
            <th>Departman İd</th>
            <th>Departman Ad</th>
            
        </tr>

    </thead>
    @*<tbody>
        @foreach (var getir in Model)
        {
            <tr>
                <td>@getir.id</td>
                <td>@getir.ad</td>
                <td><a href="Departman/guncelle/@getir.id">Güncelle</a></td>
                <td><a href="Departman/sil/@getir.id">Sil</a></td>
            </tr>
        }

    </tbody>*@
@*
</table>*@

personelimmvc/Views/personel/Index.cshtml
@model List<personelimmvc.Models.EntityFramework.personel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/shared/Layout.cshtml";
}

<h2>Personel sayfası</h2>
@Html.ActionLink("Yeni Personel","Yeni",null , new {@class="btn btn-success" })
@* action link ile yeni personel yazılı yeni action resultunu kullanarak bir buton yaptık *@
<table class="table table-bordered">
<thead>
<tr>
    <th>Ad</th>
    <th>Soyad</th>
    <th>Maaş</th>
    <th>Yaş</th>
    <th>Doğum Tarihi</th>
    <th>Cinsiyet</th>
    <th>Evlimi</th>
</tr>

</thead>
    <tbody>
@foreach (var getir in Model)
{
    <tr>
        <td>@getir.ad</td>
        <td>@getir.soyad</td>
        <td>@getir.maas</td>
        <td>@(DateTime.Now.Year-getir.dogumtarihi.Value.Year)</td>
        @*yaşı hesaplarken bugünün tarihinden veritabanından gelen doğum tarihi çıkarılıyor*@
        <td>@getir.dogumtarihi.Value.ToString("dd-MM-yyyy")</td>

        <td>@(getir.cinsiyet==true?"Erkek":"Kadın")</td>
        @* cinsiyetten gelen değer 1 ise erkek değilse kadın yazdır*@
        <td>@(getir.evlimi==true?"Evli":"Bekar")</td>
        <td><a class="btn btn-success" href="/personel/guncelle/">Güncelle</a></td>
        <td><a class="btn btn-danger" href="/personel/Sil/">Sil</a></td>
    </tr>
}

    </tbody>
</table>

personelimmvc/Views/personel/Personelform.cshtml
@model personelimmvc.view_models.Personelformviewmodels
@* model olarak personelformviewmodels.cs sayfasını aldık. view  model yapısını 
dropdown kullanacağımız için işleme aldık *@
@{
    ViewBag.Title = "Personelform";
    Layout = "~/Views/shared/Layout.cshtml";
}
@using (Html.BeginForm("kaydet","personel", FormMethod.Post)) {@*  form açtık
 kaydet bizi action result ismimiz personel ise kaydet actionresultumuzun bulunduğu conroler
  html helper yapısını kullandık         *@

<div class="form-group">
@Html.LabelFor(m=>m.personel.ad)
@Html.TextBoxFor(m=>m.personel.ad , new {@class="form-control" })
@*class ile textboxa özellik verdik*@
@* yukarda bir adet label ve 1 adet texboxa personelformviewmodels.cs den gelen 
  personeller propertisi adında tanımlanan metottan ad kısımlarını getirdik  *@
</div>
<div class="form-group">
    @Html.LabelFor(m => m.personel.soyad)
    @Html.TextBoxFor(m => m.personel.soyad, new { @class = "form-control" })

</div>
<div class="form-group">@Html.LabelFor(m=>m.personel.departmanid)
  
@Html.DropDownListFor(m => m.personel.departmanid, new SelectList(Model.departmanlar, "id","ad"),"departman seçiniz", new {@class="form-control" })
    @*yukarıda drowownlist olışturudu içine de personelcontrolerda yeni actionresultundan gelen Model ile departmanlardan
         id ve ad kısımları selectlist yani seçilebilir liste şeklinde alındı
        m => m.personeller.departmanid demek modelin (m ile gösterilir model)
    departmanid özelliği için *@
</div>

<div class="form-group">
    @Html.LabelFor(m => m.personel.maas)
    @Html.TextBoxFor(m => m.personel.maas, new { @class = "form-control" })

</div>

<div class="form-group">
    @Html.LabelFor(m => m.personel.dogumtarihi)
    @Html.TextBoxFor(m => m.personel.dogumtarihi, new { @class = "form-control" })

</div>
<div class="radio"> <label>
    @Html.RadioButtonFor(m => m.personel.cinsiyet, true)Erkek
</label>
</div>
@*radio buton için eğer personeller tablosundan cinsiyet değeri true ise erkek seçilmiş olsun*@
    <div class="radio">
        <label>
            @Html.RadioButtonFor(m => m.personel.cinsiyet, false)Kadın
        </label>
</div>
   <div class="checkbox">
       <label>
           @Html.CheckBoxFor(m => m.personel.evlimi.Value)Evliyseniz seçiniz
       </label>   
      

       </div>
       <button type="submit" class="btn btn-default">Kaydet</button>
}

personelimmvc/Views/shared/Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Layout</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
   
</head>
<body>
   @Html.Partial("navbar")
    <div>
        @RenderBody() 
    </div>

    <script src="~/scripts/jquery-1.9.1.min.js"></script>

    <script src="~/scripts/bootstrap.min.js"></script>

   
</body>
</html>

personelimmvc/Views/shared/navbar.cshtml
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">WebSiteName</a>
        </div>
        <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#">Page 1</a></li>
            <li><a href="#">Page 2</a></li>
            <li><a href="#">Page 3</a></li>
        </ul>
    </div>
</nav>